apiVersion: batch/v1
kind: Job
metadata:
  name: dble-vert-sldr-job
spec:
  template:
    spec:
      containers:
      - name: dble-vert-sldr-job
        image: yash5090/dble-vert-sldr:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
